// Code generated by protoc-gen-go. DO NOT EDIT.
// source: teachings/teachings.proto

package teachings

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeachingRequest struct {
	CategorySlug         string   `protobuf:"bytes,1,opt,name=categorySlug,proto3" json:"categorySlug,omitempty"`
	Text                 []string `protobuf:"bytes,2,rep,name=text,proto3" json:"text,omitempty"`
	MediaBase64          []string `protobuf:"bytes,3,rep,name=mediaBase64,proto3" json:"mediaBase64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeachingRequest) Reset()         { *m = TeachingRequest{} }
func (m *TeachingRequest) String() string { return proto.CompactTextString(m) }
func (*TeachingRequest) ProtoMessage()    {}
func (*TeachingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c9aefcc6dd6cc46, []int{0}
}

func (m *TeachingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeachingRequest.Unmarshal(m, b)
}
func (m *TeachingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeachingRequest.Marshal(b, m, deterministic)
}
func (m *TeachingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeachingRequest.Merge(m, src)
}
func (m *TeachingRequest) XXX_Size() int {
	return xxx_messageInfo_TeachingRequest.Size(m)
}
func (m *TeachingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeachingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeachingRequest proto.InternalMessageInfo

func (m *TeachingRequest) GetCategorySlug() string {
	if m != nil {
		return m.CategorySlug
	}
	return ""
}

func (m *TeachingRequest) GetText() []string {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *TeachingRequest) GetMediaBase64() []string {
	if m != nil {
		return m.MediaBase64
	}
	return nil
}

type TeachingSlug struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeachingSlug) Reset()         { *m = TeachingSlug{} }
func (m *TeachingSlug) String() string { return proto.CompactTextString(m) }
func (*TeachingSlug) ProtoMessage()    {}
func (*TeachingSlug) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c9aefcc6dd6cc46, []int{1}
}

func (m *TeachingSlug) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeachingSlug.Unmarshal(m, b)
}
func (m *TeachingSlug) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeachingSlug.Marshal(b, m, deterministic)
}
func (m *TeachingSlug) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeachingSlug.Merge(m, src)
}
func (m *TeachingSlug) XXX_Size() int {
	return xxx_messageInfo_TeachingSlug.Size(m)
}
func (m *TeachingSlug) XXX_DiscardUnknown() {
	xxx_messageInfo_TeachingSlug.DiscardUnknown(m)
}

var xxx_messageInfo_TeachingSlug proto.InternalMessageInfo

func (m *TeachingSlug) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type EmptyPayload struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyPayload) Reset()         { *m = EmptyPayload{} }
func (m *EmptyPayload) String() string { return proto.CompactTextString(m) }
func (*EmptyPayload) ProtoMessage()    {}
func (*EmptyPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c9aefcc6dd6cc46, []int{2}
}

func (m *EmptyPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyPayload.Unmarshal(m, b)
}
func (m *EmptyPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyPayload.Marshal(b, m, deterministic)
}
func (m *EmptyPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyPayload.Merge(m, src)
}
func (m *EmptyPayload) XXX_Size() int {
	return xxx_messageInfo_EmptyPayload.Size(m)
}
func (m *EmptyPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyPayload.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyPayload proto.InternalMessageInfo

type Teaching struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	CategorySlug         string   `protobuf:"bytes,2,opt,name=categorySlug,proto3" json:"categorySlug,omitempty"`
	Text                 []string `protobuf:"bytes,3,rep,name=text,proto3" json:"text,omitempty"`
	MediaBase64          []string `protobuf:"bytes,4,rep,name=mediaBase64,proto3" json:"mediaBase64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Teaching) Reset()         { *m = Teaching{} }
func (m *Teaching) String() string { return proto.CompactTextString(m) }
func (*Teaching) ProtoMessage()    {}
func (*Teaching) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c9aefcc6dd6cc46, []int{3}
}

func (m *Teaching) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Teaching.Unmarshal(m, b)
}
func (m *Teaching) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Teaching.Marshal(b, m, deterministic)
}
func (m *Teaching) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Teaching.Merge(m, src)
}
func (m *Teaching) XXX_Size() int {
	return xxx_messageInfo_Teaching.Size(m)
}
func (m *Teaching) XXX_DiscardUnknown() {
	xxx_messageInfo_Teaching.DiscardUnknown(m)
}

var xxx_messageInfo_Teaching proto.InternalMessageInfo

func (m *Teaching) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Teaching) GetCategorySlug() string {
	if m != nil {
		return m.CategorySlug
	}
	return ""
}

func (m *Teaching) GetText() []string {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Teaching) GetMediaBase64() []string {
	if m != nil {
		return m.MediaBase64
	}
	return nil
}

func init() {
	proto.RegisterType((*TeachingRequest)(nil), "teachings.TeachingRequest")
	proto.RegisterType((*TeachingSlug)(nil), "teachings.TeachingSlug")
	proto.RegisterType((*EmptyPayload)(nil), "teachings.EmptyPayload")
	proto.RegisterType((*Teaching)(nil), "teachings.Teaching")
}

func init() { proto.RegisterFile("teachings/teachings.proto", fileDescriptor_0c9aefcc6dd6cc46) }

var fileDescriptor_0c9aefcc6dd6cc46 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0xb3, 0x6d, 0x63, 0xec, 0x94, 0x40, 0x32, 0x1e, 0x44, 0x4e, 0x64, 0x4f, 0x9c, 0x6a,
	0xa3, 0xc6, 0x83, 0x26, 0x1a, 0x89, 0x4d, 0xaf, 0x86, 0xea, 0x03, 0xac, 0x30, 0x41, 0x22, 0x15,
	0x84, 0xad, 0x29, 0xcf, 0xe3, 0x8b, 0x1a, 0x89, 0x94, 0xc5, 0x2e, 0x46, 0xbd, 0x0d, 0xb3, 0xb3,
	0xff, 0x7e, 0xf3, 0x25, 0xc0, 0x91, 0x24, 0x11, 0x3e, 0x25, 0x2f, 0x71, 0x79, 0xbc, 0xad, 0xa6,
	0x79, 0x91, 0xc9, 0x0c, 0xc7, 0xdb, 0x06, 0x7f, 0x06, 0xeb, 0xfe, 0xeb, 0x23, 0xa0, 0xd7, 0x35,
	0x95, 0x12, 0x39, 0x18, 0xa1, 0x90, 0x14, 0x67, 0x45, 0xb5, 0x4c, 0xd7, 0xb1, 0xcd, 0x5c, 0xe6,
	0x8d, 0x83, 0x4e, 0x0f, 0x11, 0x46, 0x92, 0x36, 0xd2, 0x1e, 0xb8, 0x43, 0x6f, 0x1c, 0xd4, 0x35,
	0xba, 0x30, 0x59, 0x51, 0x94, 0x08, 0x5f, 0x94, 0x74, 0x7e, 0x66, 0x0f, 0xeb, 0x23, 0xb5, 0xc5,
	0x39, 0x18, 0xcd, 0x63, 0x4d, 0x4a, 0xd9, 0xbe, 0x50, 0xd7, 0xdc, 0x04, 0x63, 0xbe, 0xca, 0x65,
	0x75, 0x27, 0xaa, 0x34, 0x13, 0x11, 0xdf, 0xc0, 0x7e, 0x73, 0x47, 0x37, 0xbf, 0x43, 0x3b, 0xf8,
	0x81, 0x76, 0xd8, 0x4f, 0x3b, 0xda, 0xa1, 0x3d, 0x79, 0x1f, 0xb5, 0x6e, 0x96, 0x54, 0xbc, 0x25,
	0x21, 0xe1, 0x02, 0x8c, 0x9b, 0x28, 0x6a, 0xba, 0x25, 0x3a, 0xd3, 0xd6, 0xed, 0x37, 0x8f, 0xce,
	0xa1, 0xe6, 0xec, 0x13, 0xc7, 0x63, 0x33, 0x86, 0x57, 0x60, 0x2c, 0x48, 0xb6, 0x41, 0xea, 0xb0,
	0xba, 0xbf, 0x73, 0xa0, 0x49, 0x99, 0x31, 0xbc, 0x06, 0xeb, 0x21, 0x8f, 0x84, 0xa4, 0x36, 0x42,
	0x37, 0xa9, 0xbd, 0x5e, 0x03, 0xcc, 0xc1, 0xba, 0xa5, 0x94, 0xd4, 0x80, 0x3e, 0x60, 0xa7, 0x0f,
	0xce, 0x63, 0xe8, 0xc3, 0x44, 0x11, 0xf2, 0x2f, 0x1f, 0x78, 0x09, 0x13, 0xc5, 0x45, 0x3f, 0x86,
	0x6e, 0x17, 0xbc, 0x00, 0xb3, 0x2b, 0xe2, 0xf7, 0x1e, 0xd0, 0x07, 0xb3, 0xeb, 0xe0, 0xef, 0x0a,
	0x1e, 0xf7, 0xea, 0x5f, 0xea, 0xf4, 0x23, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xab, 0x05, 0x09, 0x6f,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TeachingServiceClient is the client API for TeachingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeachingServiceClient interface {
	AddTeachings(ctx context.Context, opts ...grpc.CallOption) (TeachingService_AddTeachingsClient, error)
	GetTeachings(ctx context.Context, in *EmptyPayload, opts ...grpc.CallOption) (TeachingService_GetTeachingsClient, error)
	UpdateTeachings(ctx context.Context, opts ...grpc.CallOption) (TeachingService_UpdateTeachingsClient, error)
	DeleteTeachings(ctx context.Context, opts ...grpc.CallOption) (TeachingService_DeleteTeachingsClient, error)
	AddTeaching(ctx context.Context, in *TeachingRequest, opts ...grpc.CallOption) (*TeachingSlug, error)
	GetTeaching(ctx context.Context, in *TeachingSlug, opts ...grpc.CallOption) (*Teaching, error)
	UpdateTeaching(ctx context.Context, in *Teaching, opts ...grpc.CallOption) (*Teaching, error)
	DeleteTeaching(ctx context.Context, in *TeachingSlug, opts ...grpc.CallOption) (*EmptyPayload, error)
}

type teachingServiceClient struct {
	cc *grpc.ClientConn
}

func NewTeachingServiceClient(cc *grpc.ClientConn) TeachingServiceClient {
	return &teachingServiceClient{cc}
}

func (c *teachingServiceClient) AddTeachings(ctx context.Context, opts ...grpc.CallOption) (TeachingService_AddTeachingsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TeachingService_serviceDesc.Streams[0], "/teachings.TeachingService/AddTeachings", opts...)
	if err != nil {
		return nil, err
	}
	x := &teachingServiceAddTeachingsClient{stream}
	return x, nil
}

type TeachingService_AddTeachingsClient interface {
	Send(*TeachingRequest) error
	Recv() (*TeachingSlug, error)
	grpc.ClientStream
}

type teachingServiceAddTeachingsClient struct {
	grpc.ClientStream
}

func (x *teachingServiceAddTeachingsClient) Send(m *TeachingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *teachingServiceAddTeachingsClient) Recv() (*TeachingSlug, error) {
	m := new(TeachingSlug)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *teachingServiceClient) GetTeachings(ctx context.Context, in *EmptyPayload, opts ...grpc.CallOption) (TeachingService_GetTeachingsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TeachingService_serviceDesc.Streams[1], "/teachings.TeachingService/GetTeachings", opts...)
	if err != nil {
		return nil, err
	}
	x := &teachingServiceGetTeachingsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TeachingService_GetTeachingsClient interface {
	Recv() (*Teaching, error)
	grpc.ClientStream
}

type teachingServiceGetTeachingsClient struct {
	grpc.ClientStream
}

func (x *teachingServiceGetTeachingsClient) Recv() (*Teaching, error) {
	m := new(Teaching)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *teachingServiceClient) UpdateTeachings(ctx context.Context, opts ...grpc.CallOption) (TeachingService_UpdateTeachingsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TeachingService_serviceDesc.Streams[2], "/teachings.TeachingService/UpdateTeachings", opts...)
	if err != nil {
		return nil, err
	}
	x := &teachingServiceUpdateTeachingsClient{stream}
	return x, nil
}

type TeachingService_UpdateTeachingsClient interface {
	Send(*Teaching) error
	Recv() (*Teaching, error)
	grpc.ClientStream
}

type teachingServiceUpdateTeachingsClient struct {
	grpc.ClientStream
}

func (x *teachingServiceUpdateTeachingsClient) Send(m *Teaching) error {
	return x.ClientStream.SendMsg(m)
}

func (x *teachingServiceUpdateTeachingsClient) Recv() (*Teaching, error) {
	m := new(Teaching)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *teachingServiceClient) DeleteTeachings(ctx context.Context, opts ...grpc.CallOption) (TeachingService_DeleteTeachingsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TeachingService_serviceDesc.Streams[3], "/teachings.TeachingService/DeleteTeachings", opts...)
	if err != nil {
		return nil, err
	}
	x := &teachingServiceDeleteTeachingsClient{stream}
	return x, nil
}

type TeachingService_DeleteTeachingsClient interface {
	Send(*TeachingSlug) error
	CloseAndRecv() (*EmptyPayload, error)
	grpc.ClientStream
}

type teachingServiceDeleteTeachingsClient struct {
	grpc.ClientStream
}

func (x *teachingServiceDeleteTeachingsClient) Send(m *TeachingSlug) error {
	return x.ClientStream.SendMsg(m)
}

func (x *teachingServiceDeleteTeachingsClient) CloseAndRecv() (*EmptyPayload, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EmptyPayload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *teachingServiceClient) AddTeaching(ctx context.Context, in *TeachingRequest, opts ...grpc.CallOption) (*TeachingSlug, error) {
	out := new(TeachingSlug)
	err := c.cc.Invoke(ctx, "/teachings.TeachingService/AddTeaching", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teachingServiceClient) GetTeaching(ctx context.Context, in *TeachingSlug, opts ...grpc.CallOption) (*Teaching, error) {
	out := new(Teaching)
	err := c.cc.Invoke(ctx, "/teachings.TeachingService/GetTeaching", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teachingServiceClient) UpdateTeaching(ctx context.Context, in *Teaching, opts ...grpc.CallOption) (*Teaching, error) {
	out := new(Teaching)
	err := c.cc.Invoke(ctx, "/teachings.TeachingService/UpdateTeaching", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teachingServiceClient) DeleteTeaching(ctx context.Context, in *TeachingSlug, opts ...grpc.CallOption) (*EmptyPayload, error) {
	out := new(EmptyPayload)
	err := c.cc.Invoke(ctx, "/teachings.TeachingService/DeleteTeaching", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeachingServiceServer is the server API for TeachingService service.
type TeachingServiceServer interface {
	AddTeachings(TeachingService_AddTeachingsServer) error
	GetTeachings(*EmptyPayload, TeachingService_GetTeachingsServer) error
	UpdateTeachings(TeachingService_UpdateTeachingsServer) error
	DeleteTeachings(TeachingService_DeleteTeachingsServer) error
	AddTeaching(context.Context, *TeachingRequest) (*TeachingSlug, error)
	GetTeaching(context.Context, *TeachingSlug) (*Teaching, error)
	UpdateTeaching(context.Context, *Teaching) (*Teaching, error)
	DeleteTeaching(context.Context, *TeachingSlug) (*EmptyPayload, error)
}

func RegisterTeachingServiceServer(s *grpc.Server, srv TeachingServiceServer) {
	s.RegisterService(&_TeachingService_serviceDesc, srv)
}

func _TeachingService_AddTeachings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeachingServiceServer).AddTeachings(&teachingServiceAddTeachingsServer{stream})
}

type TeachingService_AddTeachingsServer interface {
	Send(*TeachingSlug) error
	Recv() (*TeachingRequest, error)
	grpc.ServerStream
}

type teachingServiceAddTeachingsServer struct {
	grpc.ServerStream
}

func (x *teachingServiceAddTeachingsServer) Send(m *TeachingSlug) error {
	return x.ServerStream.SendMsg(m)
}

func (x *teachingServiceAddTeachingsServer) Recv() (*TeachingRequest, error) {
	m := new(TeachingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TeachingService_GetTeachings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyPayload)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TeachingServiceServer).GetTeachings(m, &teachingServiceGetTeachingsServer{stream})
}

type TeachingService_GetTeachingsServer interface {
	Send(*Teaching) error
	grpc.ServerStream
}

type teachingServiceGetTeachingsServer struct {
	grpc.ServerStream
}

func (x *teachingServiceGetTeachingsServer) Send(m *Teaching) error {
	return x.ServerStream.SendMsg(m)
}

func _TeachingService_UpdateTeachings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeachingServiceServer).UpdateTeachings(&teachingServiceUpdateTeachingsServer{stream})
}

type TeachingService_UpdateTeachingsServer interface {
	Send(*Teaching) error
	Recv() (*Teaching, error)
	grpc.ServerStream
}

type teachingServiceUpdateTeachingsServer struct {
	grpc.ServerStream
}

func (x *teachingServiceUpdateTeachingsServer) Send(m *Teaching) error {
	return x.ServerStream.SendMsg(m)
}

func (x *teachingServiceUpdateTeachingsServer) Recv() (*Teaching, error) {
	m := new(Teaching)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TeachingService_DeleteTeachings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeachingServiceServer).DeleteTeachings(&teachingServiceDeleteTeachingsServer{stream})
}

type TeachingService_DeleteTeachingsServer interface {
	SendAndClose(*EmptyPayload) error
	Recv() (*TeachingSlug, error)
	grpc.ServerStream
}

type teachingServiceDeleteTeachingsServer struct {
	grpc.ServerStream
}

func (x *teachingServiceDeleteTeachingsServer) SendAndClose(m *EmptyPayload) error {
	return x.ServerStream.SendMsg(m)
}

func (x *teachingServiceDeleteTeachingsServer) Recv() (*TeachingSlug, error) {
	m := new(TeachingSlug)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TeachingService_AddTeaching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeachingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeachingServiceServer).AddTeaching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teachings.TeachingService/AddTeaching",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeachingServiceServer).AddTeaching(ctx, req.(*TeachingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeachingService_GetTeaching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeachingSlug)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeachingServiceServer).GetTeaching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teachings.TeachingService/GetTeaching",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeachingServiceServer).GetTeaching(ctx, req.(*TeachingSlug))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeachingService_UpdateTeaching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Teaching)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeachingServiceServer).UpdateTeaching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teachings.TeachingService/UpdateTeaching",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeachingServiceServer).UpdateTeaching(ctx, req.(*Teaching))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeachingService_DeleteTeaching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeachingSlug)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeachingServiceServer).DeleteTeaching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teachings.TeachingService/DeleteTeaching",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeachingServiceServer).DeleteTeaching(ctx, req.(*TeachingSlug))
	}
	return interceptor(ctx, in, info, handler)
}

var _TeachingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "teachings.TeachingService",
	HandlerType: (*TeachingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTeaching",
			Handler:    _TeachingService_AddTeaching_Handler,
		},
		{
			MethodName: "GetTeaching",
			Handler:    _TeachingService_GetTeaching_Handler,
		},
		{
			MethodName: "UpdateTeaching",
			Handler:    _TeachingService_UpdateTeaching_Handler,
		},
		{
			MethodName: "DeleteTeaching",
			Handler:    _TeachingService_DeleteTeaching_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddTeachings",
			Handler:       _TeachingService_AddTeachings_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetTeachings",
			Handler:       _TeachingService_GetTeachings_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateTeachings",
			Handler:       _TeachingService_UpdateTeachings_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DeleteTeachings",
			Handler:       _TeachingService_DeleteTeachings_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "teachings/teachings.proto",
}
